เทส123

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -2,23 +2,23 @@ name: hello-world
 on: push
 jobs:
   my-job:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-      - name: set nodejs
-        uses: actions/setup-node@v2
-        with:
-          node-version: '18'
+      runs-on: ubuntu-latest
+      steps:
+        - name: Checkout code
+          uses: actions/checkout@v2
+        - name: set nodejs
+          uses: actions/setup-node@v2
+          with:
+            node-version: '18'
 
-      - name: install package json
-        run: npm install
-          
-      - name: Run Testing
-        run:
-          output=$(node dist/Test1.js)
+        - name: install package json
+          run: npm install
 
-          if [ $output -ne ผิด ]; then
-            echo "ไม่บอก:code $output"
-            exit 1
-          fi
+        - name: Run testing
+          run: |
+            output=$(node dist/Test1.js)
+
+            if [ $output -ne 0 ]; then
+              echo "Error: code $output"
+              exit 1
+            fi
